### ISSUE TITLE
Sept 25 Call Action Items

### ISSUE THREAD

**Issue by brandonbrown** [mattdevio/moolahlah#11]
Just as a quick reminder from our call. If I'm forgetting anything or may have misremembered, please feel free to respond to this issue.

> Work on moolahlah will continue into the October Term.

Adjusted Week 1 Milestone:
- [x] Primary Goal 1: Design comps to cover all features planned for MVP
- [x] Primary Goal 2: Features planned as Github Issues
- [x] Secondary Goal 1: User stories added to Github Projects, Trello, or other third-party project planning service
- [ ] Secondary Goal 2: Interactive prototype from XD, Sketch, or another image based prototyping tool.
- [x] Bonus (not discussed on call): Video Presentation of comps or prototype by Saturday. To be shared with instructors and faculty if created for further clarity of project.

**Comment by mattdevio** [comment]
Youtube Video:
https://youtu.be/iUD0kTfJlB8
