### ISSUE TITLE
As a developer, I would like to use a relational database so that data is organized and easy to manage.

### ISSUE THREAD

**Issue by mattdevio** [mattdevio/moolahlah#43]
**Background :** The current platform uses mongo with the mongoose ORM to store data. No real thought was given to this decision and it has been determined that a relational database would be better. We would like to switch to a MySQL db with the [Sequelize.js ORM](http://docs.sequelizejs.com/). Current database schema will need to be ported to the new platform.

**AC :**
* Sequelize.js has been used to setup the project for MySQL
* Documentation has been updated to reflect the new DB change
* Feature has been tested on the test server

**Comment by mattdevio** [comment]
Working on this feature now! 💯 

**Branch:** [Feature/RelationalDB](https://github.com/mattdevio/moolahlah/tree/Feature/RelationalDB)

**Comment by brandonbrown** [comment]
See note on #52

**Comment by mattdevio** [comment]
@brandonbrown Acknowledged, I will update the stories today.

After much testing, it was determined that Sequelize.js is awful. Using [Knex.js](https://knexjs.org/) and [Objection.js](https://vincit.github.io/objection.js/) instead. Initial conversion has been done. Need to figure out validation and rebuild apis.
