### ISSUE TITLE
As a user I would like to recover lost account information

### ISSUE THREAD

**Issue by mattdevio** [mattdevio/moolahlah#47]
**Background** Right now, users can sign up and login, but they have no way of recovering their account if the information is lost. I would like an email sent to them that lets the user reset their password.

**AC:**
* Reset password link is added to the login form
* Reset password sends an email the registered email address
* Email contains link to reset password
* Reset password form is created and working
* Feature is tested on TEST server

**Comment by brandonbrown** [comment]
Adjusted the title to clarify the user story from the functional requirements.
