### ISSUE TITLE
As a user, I would like an overview of spending while designing the budget.

### ISSUE THREAD

**Issue by mattdevio** [mattdevio/moolahlah#48]
**Background:** Each category will have multiple line items in it. A total / overview section will let the user see how much they are spending

**AC:**
* Category total is displayed to the user.
* Overall total is also displayed
* Has been tested on TEST server

**Comment by brandonbrown** [comment]
The "List" and "Total" pieces of the original title should be addressed as features to achieve the completion of the user story.
