### ISSUE TITLE
As a user, I would like to compare budget categories visually

### ISSUE THREAD

**Issue by mattdevio** [mattdevio/moolahlah#49]
**Background:** Each category represents a percent of the total income in the budget. I would like a pie chart that shows the usage of each category as port of the whole.

**AC:**
* Each category is represented by a color on on part of the pie chart
* Has been tested on TEST server.

**Comment by brandonbrown** [comment]
Simplifying the title so it's easier for others to understand.

**Comment by brandonbrown** [comment]
In addition, some budget types won't make sense as a pie chart. Consider the amount of categories a user may have. A pie chart trying to display more than 8 pieces of information meaningfully will be tough. Maybe there's an option for users to change graph types, or you can decide that different budgets may require different types of visualizations.
