### ISSUE TITLE
As a user, I would like to compare my budget to real life spending.

### ISSUE THREAD

**Issue by mattdevio** [mattdevio/moolahlah#50]
**Background:** After a user plans their budget, they need to be able to add their real life transactions to so we can see how well they are doing.

**AC:**
* A form is created that allows users to enter their transactions
* Transactions are saved to the database
* As user can decide which category the transaction is assigned to
* The feature has been tested on the TEST server.

**Comment by brandonbrown** [comment]
We want the user stories to be more generalized so that you can add all functional requirements beneath it. Having it directed to the "add" action means that any functionality such as modify, delete, or otherwise change that isn't "add" would not fit within this user story.
